# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeed',
            name='pass_fail',
            field=models.BooleanField(default=False),
        ),
    ]
