# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_postfeed_pass_fail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfeed',
            old_name='pass_fail',
            new_name='fail',
        ),
    ]
