# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='muting_value',
            field=models.FloatField(default=5.0),
        ),
    ]
